chore: improve test scripts, make task and readme

diff --git a/test-manual/Makefile b/test-manual/Makefile
--- a/test-manual/Makefile
+++ b/test-manual/Makefile
@@ -1,44 +1,26 @@
 DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
 
+HELIUS_LASER_DIR := $(DIR)helius-laser
+HELIUS_LASER_SH_DIR := $(HELIUS_LASER_DIR)/sh
+
 fmt:
 	cargo +nightly fmt -- --config-path $(DIR)rustfmt-nightly.toml
 
 list:
 	@LC_ALL=C $(MAKE) -pRrq -f $(firstword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/(^|\n)# Files(\n|$$)/,/(^|\n)# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$'
 
-manual-test-laser:
-	@echo "Checking for Helius API key"
-	@if [ -z "$$HELIUS_API_KEY" ]; then \
-		echo "Error: HELIUS_API_KEY environment variable not set"; \
+test-laser:
+	@if [ -z "$$HELIUS_API_KEY" ] && [ -z "$$TRITON_API_KEY" ]; then \
+		echo "Error: HELIUS_API_KEY or TRITON_API_KEY environment variable not set"; \
 		exit 1; \
 	fi
-	@echo
-	@echo "## Extracting keypair path..."
-	$(eval KEYPAIR_PATH := $(shell solana config get | grep "Keypair Path:" | cut -d: -f2 | xargs))
-	@echo "Keypair path: $(KEYPAIR_PATH)"
-	@echo
-	@echo "## Airdropping 1 SOL to pubkey on devnet"
-	$(eval PUBKEY := $(shell solana-keygen pubkey $(KEYPAIR_PATH)))
-	@echo "Pubkey: $(PUBKEY)"
-	@echo "Airdropping 1 SOL to $(PUBKEY)..."
-	@solana airdrop 1 $(PUBKEY) --url devnet || true
-	@echo
-	@echo "## Creating validator config (0600) ..."
-	@install -m 600 /dev/null /tmp/mb-test-laser.toml
-	@{ \
-		echo "[accounts]"; \
-		echo "remote.url = \"https://devnet.helius-rpc.com/?api-key=$(HELIUS_API_KEY)\""; \
-		echo "remote.ws-url = [\"https://laserstream-devnet-ewr.helius-rpc.com?api-key=$(HELIUS_API_KEY)\"]"; \
-		echo; \
-		echo "[rpc]"; \
-		echo "addr = \"0.0.0.0\""; \
-		echo "port = 9988"; \
-	} >> /tmp/mb-test-laser.toml
+	$(eval KEYPAIR_PATH := $(shell $(HELIUS_LASER_SH_DIR)/01_extract_keypair_path.sh))
+	$(HELIUS_LASER_SH_DIR)/02_airdrop.sh $(KEYPAIR_PATH) || true
+	$(HELIUS_LASER_SH_DIR)/03_create-config.sh
 	@echo
 	@echo "## Starting validator in background..."
 	RUST_LOG=warn,magicblock=info,magicblock_chainlink=debug,magicblock_accounts=debug \
 			cargo run --bin magicblock-validator --manifest-path=$(DIR)../Cargo.toml \
-			-- --ledger-resume-strategy-kind=reset \
 			-- /tmp/mb-test-laser.toml \
 			> /tmp/validator.log 2>&1 &
 	@echo $$! > /tmp/validator.pid
@@ -47,7 +29,6 @@ manual-test-laser:
 	@until solana cluster-version --url http://127.0.0.1:9988 >/dev/null 2>&1; do \
 		sleep 1; \
 	done
-	@echo
 	@echo "## Running laser test..."
 	@KEYPAIR_PATH=$(KEYPAIR_PATH) RUST_LOG=info \
 		cargo run --bin helius-laser || { \
@@ -63,4 +44,4 @@ manual-test-laser:
 		rm /tmp/validator.pid /tmp/validator.log /tmp/mb-test-laser.toml ; \
 	fi
 
-.PHONY: fmt list manual-test-laser
+.PHONY: fmt list test-laser
