debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -68,44 +68,44 @@ jobs:
           make ci-lint
 
 
-  unit-tests:
-    name: Unit Tests
-    runs-on: self-hosted
-    # Su push sempre; su PR solo se non è draft
-    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
-    needs: [format, lint]
-    steps:
-      - name: Checkout magicblock-validator
-        uses: actions/checkout@v5
-        with:
-          fetch-depth: 1
-
-      - name: Install Rust toolchain
-        run: |
-          rustup toolchain install 1.91.1 --profile default
-          rustup default 1.91.1
-          rustc --version
-          cargo --version
-
-      - name: Install cargo-expand
-        run: |
-          if ! command -v cargo-expand &> /dev/null; then
-            echo "cargo-expand not found, installing..."
-            cargo install cargo-expand
-          else
-            echo "cargo-expand already installed"
-          fi
-
-      - name: Run unit tests
-        run: |
-          make ci-test-unit
+#  unit-tests:
+#    name: Unit Tests
+#    runs-on: self-hosted
+#    # Su push sempre; su PR solo se non è draft
+#    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
+#    needs: [format, lint]
+#    steps:
+#      - name: Checkout magicblock-validator
+#        uses: actions/checkout@v5
+#        with:
+#          fetch-depth: 1
+#
+#      - name: Install Rust toolchain
+#        run: |
+#          rustup toolchain install 1.91.1 --profile default
+#          rustup default 1.91.1
+#          rustc --version
+#          cargo --version
+#
+#      - name: Install cargo-expand
+#        run: |
+#          if ! command -v cargo-expand &> /dev/null; then
+#            echo "cargo-expand not found, installing..."
+#            cargo install cargo-expand
+#          else
+#            echo "cargo-expand already installed"
+#          fi
+#
+#      - name: Run unit tests
+#        run: |
+#          make ci-test-unit
 
   integration-tests:
     name: Integration Tests - ${{ matrix.batch_tests }}
     runs-on: self-hosted
     # Su push sempre; su PR solo se non è draft
     if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
-    needs: [format, lint, unit-tests]
+    needs: [format, lint]
     strategy:
       fail-fast: false
       matrix:
@@ -147,7 +147,6 @@ jobs:
     needs:
       - format
       - lint
-      - unit-tests
       - integration-tests
     steps:
       - name: Check all jobs status
